In [1]:
import numpy as np
import torch

#### 1D Array with Numpy

In [2]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [3]:
print(t.ndim)
print(t.shape)

1
(7,)


#### 2D Array with Numpy


In [4]:
t = np.array([[1., 2., 3.],[4., 5., 6.],[7., 8., 9.],[10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [5]:
print(t.ndim)
print(t.shape)

2
(4, 3)


#### 1D Array with PyTorch

In [6]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [7]:
print(t.dim())
print(t.shape)
print(t.size())


1
torch.Size([7])
torch.Size([7])


#### 2D Array with PyTorch

In [8]:
t = torch.FloatTensor([[1., 2., 3.],[4., 5., 6.],[7., 8., 9.],[10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [9]:
print(t.dim())
print(t.shape)
print(t.size())


2
torch.Size([4, 3])
torch.Size([4, 3])


### Broadcasting


In [10]:
# same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [11]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [12]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


#### Mul vs. Matmul

In [13]:
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print('Matmul:\n' , m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print('Mul:\n', m1.mul(m2))

-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
Matmul:
 tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
Mul:
 tensor([[1., 2.],
        [6., 8.]])


#### Mean

In [14]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [15]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [16]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [17]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


#### Sum

In [18]:
t = torch.FloatTensor([[1,2],[3,4],[5,6]])
t

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [19]:
print(t.sum())
print(t.sum(dim=0))  # 0번째 차원 행을 제거
print(t.sum(dim=1))  # 1번째 차원 열을 제거
print(t.sum(dim=-1)) # 마지막 차원(열)을 제거한다는 의미 

tensor(21.)
tensor([ 9., 12.])
tensor([ 3.,  7., 11.])
tensor([ 3.,  7., 11.])


#### Max and Argmax

In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.max()) # Returns one value: max

tensor(4.)


In [22]:
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1]) # 최대값의 인덱스

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [23]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


#### View : np.reshape와 같은 기능

In [25]:
t = np.array([[[0, 1, 2] ,[3, 4, 5]],[[6, 7, 8],[9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [31]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [32]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


#### Squeeze : 해당 dimension에 element의 개수가 1인 경우에 해당 dimension을 제거

In [33]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [34]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


#### Unsqueeze : 내가 원하는 dimension에 1을 넣어줌

In [35]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [37]:
# dim=0에 1을 넣어줌 
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [38]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [39]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [41]:
# 마지막 dim(dim=1)에 1을 넣어줌 
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


#### Type Casting

In [42]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [43]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [49]:
bt = (lt == 3)
print(bt)
print(bt.float())

tensor([False, False,  True, False])
tensor([0., 0., 1., 0.])


In [44]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


#### Concatenate

In [50]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y],dim = 0))
print(torch.cat([x,y],dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


#### Stacking

In [51]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [57]:
print(torch.cat([x, y, z]))

tensor([1., 4., 2., 5., 3., 6.])


In [52]:
print(torch.stack([x, y, z])) # default dim = 0
print(torch.stack([x, y, z],dim = 1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [53]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


#### Ones and Zeros : x와 같은 shape의 0, 1로만 이루어진 tensor 생성

In [60]:
x = torch.FloatTensor([[0, 1, 2],[2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [59]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### In-place Operation : 메모리를 사용하지 않고 기존의 텐서에 값을 변형 

In [62]:
x = torch.FloatTensor([[1, 2],[3, 4]])

In [63]:
print(x.mul(2.)) # 메모리에 저장하지 않음 
print(x)
print(x.mul_(2.)) # 메모리에 저장
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
